version: '3.9'

services:
  gateway:
    image: traefik:v2.9
    container_name: api_gateway
    command:
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro

  db_courses:
    image: postgres:15
    container_name: db_courses
    environment:
      POSTGRES_USER: ${POSTGRES_COURSES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_COURSES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB_COURSES}
    ports:
      - "5432:5432"
    volumes:
      - db_courses_data:/var/lib/postgresql/data

  courses:
    build: ./services/courses
    container_name: courses_service
    environment:
      - DATABASE_URL=${DATABASE_COURSES_URL}
    depends_on:
      - db_courses
    labels:
      - "traefik.http.routers.courses.rule=PathPrefix(`/courses`)"
      - "traefik.http.services.courses.loadbalancer.server.port=3001"

volumes:
  db_courses_data:
