name: CI - Run Tests

on:
  push:
    branches:
      - main

jobs:
  courses-service:
    name: Test Courses Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/courses
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  enrollments-service:
    name: Test Enrollments Service
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./services/enrollments
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm run test

  
