name: CI - Build & Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build images
        run: docker-compose -f docker-compose.yml build

      - name: Run Courses Service tests
        run: docker-compose run --rm courses npm run test

      - name: Run Enrollments Service tests
        run: docker-compose run --rm enrollments npm run test
